apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-operator-helm
spec:
  replicas: 1
  selector:
    matchLabels:
      name: argocd-operator-helm
  template:
    metadata:
      labels:
        name: argocd-operator-helm
    spec:
      serviceAccountName: argocd-operator-helm
      containers:
        - name: argocd-operator-helm
          image: quay.io/disposab1e/argocd-operator-helm:v0.0.1
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "argocd-operator-helm"
