name: verify

on:
  pull_request:
    branches:
    - travis-ci

jobs:
  pull-request:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.x
      uses: actions/setup-python@v1
      with:
        python-version: '3.x'
    - name: Install Dependencies
      run: build/ci/install-deps
    - name: Verify Helm templates
      run: make helm-templates
      working-directory: ${{ github.workspace }}/build
    - name: Build Operator (dev)
      run: make operator-build-dev
      working-directory: ${{ github.workspace }}/build
    - name: Build and verify Bundle k8s (dev)
      run: make bundle-build-k8s-dev
      working-directory: ${{ github.workspace }}/build
    - name: Build and verify Bundle ocp (dev)
      run: make bundle-build-ocp-dev
      working-directory: ${{ github.workspace }}/build
    - name: Build Operator (release)
      run: make operator-build-release
      working-directory: ${{ github.workspace }}/build
    - name: Verify Bundle k8s (release)
      run: make bundle-verify-k8s-release
      working-directory: ${{ github.workspace }}/build
    - name: Build Bundle k8s (release)
      run: make bundle-build-k8s-release
      working-directory: ${{ github.workspace }}/build
    - name: Verify Bundle ocp (release)
      run: make bundle-verify-ocp-release
      working-directory: ${{ github.workspace }}/build
    - name: Build Bundle ocp (release)
      run: make bundle-build-ocp-release
      working-directory: ${{ github.workspace }}/build
    - name: Generate Guides
      run: make generate-guides
      working-directory: ${{ github.workspace }}/build
    - name: Generate Quickstarts
      run: make generate-quickstarts
      working-directory: ${{ github.workspace }}/build
    - name: Release Guides
      run: make release-guides
      working-directory: ${{ github.workspace }}/build
    - name: Release Quickstarts
      run: make release-quickstarts
      working-directory: ${{ github.workspace }}/build
